# Description: Training configuration file for CGSchnet
# This originally came from https://github.com/torchmd/torchmd-protein-thermodynamics/tree/main/Tutorials/train.yaml

activation: silu
batch_size: 16
dataset: Custom

cutoff_upper: 12.0
cutoff_lower: 3.0
derivative: true
# early_stopping_patience: 10
embedding_dimension: 128
lr: 0.001
lr_factor: 0.8
lr_min: 1.0e-06
lr_patience: 10
lr_warmup_steps: 0
model: graph-network
ngpus: -1
num_epochs: 2
num_layers: 4
num_nodes: 1
num_rbf: 18
num_workers: 8
rbf_type: expnorm
save_interval: 1
seed: 94572
test_interval: 20
log_dir: logs/
trainable_rbf: true
weight_decay: 0.0
test_size: null
train_size: 0.9
val_size: 0.1
